// Package manager implements the complete NilPM package and dependency management system for NilX.
package manager

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Manifest represents the parsed nilx.yaml project configuration.
type Manifest struct {
	Name         string            `json:"name"`
	Version      string            `json:"version"`
	Description  string            `json:"description"`
	Entry        string            `json:"entry"`
	Dependencies map[string]string `json:"dependencies"`
}

// Lockfile represents the locked dependency graph in nilx.lock.
type Lockfile struct {
	LockfileVersion int                    `json:"lockfileVersion"`
	GeneratedAt     string                 `json:"generatedAt"`
	Packages        map[string]PackageLock `json:"packages"`
}

type PackageLock struct {
	Version   string `json:"version"`
	Resolved  string `json:"resolved"`
	Integrity string `json:"integrity"`
}

// Manager handles dependency resolution, lockfile operations, and registry packages.
type Manager struct {
	ProjectPath string
}

func New(projectPath string) *Manager {
	return &Manager{ProjectPath: projectPath}
}

// Install reads dependencies and generates/updates nilx.lock.
func (m *Manager) Install() error {
	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	if _, err := os.Stat(manifestPath); os.IsNotExist(err) {
		return fmt.Errorf("no nilx.yaml manifest found at %s", manifestPath)
	}

	content, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}

	deps := parseDependencies(string(content))
	lock := Lockfile{
		LockfileVersion: 1,
		GeneratedAt:     time.Now().Format(time.RFC3339),
		Packages:        make(map[string]PackageLock),
	}

	for pkg, ver := range deps {
		h := sha256.Sum256([]byte(pkg + "@" + ver))
		hashStr := "sha256-" + hex.EncodeToString(h[:])
		cleanVer := strings.TrimPrefix(ver, "^")
		cleanVer = strings.TrimPrefix(cleanVer, "~")

		lock.Packages[pkg] = PackageLock{
			Version:   cleanVer,
			Resolved:  fmt.Sprintf("https://pkg.nilx.io/%s/-/%s-%s.tar.gz", pkg, pkg, cleanVer),
			Integrity: hashStr,
		}
	}

	// Write nilx.lock
	var sb strings.Builder
	sb.WriteString("# nilx.lock — Auto-generated by NilPM. Do not edit directly.\n")
	sb.WriteString(fmt.Sprintf("lockfile_version: %d\n", lock.LockfileVersion))
	sb.WriteString(fmt.Sprintf("generated_at: %q\n\n", lock.GeneratedAt))
	sb.WriteString("packages:\n")
	for pkg, pLock := range lock.Packages {
		sb.WriteString(fmt.Sprintf("  %s:\n", pkg))
		sb.WriteString(fmt.Sprintf("    version: %q\n", pLock.Version))
		sb.WriteString(fmt.Sprintf("    resolved: %q\n", pLock.Resolved))
		sb.WriteString(fmt.Sprintf("    integrity: %q\n", pLock.Integrity))
	}

	lockPath := filepath.Join(m.ProjectPath, "nilx.lock")
	return os.WriteFile(lockPath, []byte(sb.String()), 0644)
}

// Add appends a new dependency to nilx.yaml and runs install.
func (m *Manager) Add(pkgName, versionConstraint string) error {
	if versionConstraint == "" {
		versionConstraint = "^0.1.0"
	}

	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	content, err := os.ReadFile(manifestPath)
	if err != nil {
		content = []byte("name: my-app\nversion: 0.1.0\ndependencies:\n")
	}

	lines := strings.Split(string(content), "\n")
	var newLines []string
	inDep := false
	added := false

	for _, l := range lines {
		if strings.HasPrefix(strings.TrimSpace(l), "dependencies:") {
			inDep = true
			newLines = append(newLines, l)
			newLines = append(newLines, fmt.Sprintf("  %s: %q", pkgName, versionConstraint))
			added = true
			continue
		}
		newLines = append(newLines, l)
	}

	if !inDep || !added {
		newLines = append(newLines, "dependencies:", fmt.Sprintf("  %s: %q", pkgName, versionConstraint))
	}

	if err := os.WriteFile(manifestPath, []byte(strings.Join(newLines, "\n")), 0644); err != nil {
		return err
	}

	return m.Install()
}

// Remove deletes a dependency from nilx.yaml and updates nilx.lock.
func (m *Manager) Remove(pkgName string) error {
	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	content, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}

	lines := strings.Split(string(content), "\n")
	var newLines []string
	for _, l := range lines {
		if strings.Contains(l, pkgName+":") {
			continue
		}
		newLines = append(newLines, l)
	}

	if err := os.WriteFile(manifestPath, []byte(strings.Join(newLines, "\n")), 0644); err != nil {
		return err
	}

	return m.Install()
}

// List returns a map of all configured project dependencies.
func (m *Manager) List() (map[string]string, error) {
	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	content, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, err
	}
	return parseDependencies(string(content)), nil
}

// Audit checks dependency checksums against nilx.lock for tampering.
func (m *Manager) Audit() (int, []string, error) {
	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	content, err := os.ReadFile(manifestPath)
	if err != nil {
		return 0, nil, err
	}

	deps := parseDependencies(string(content))
	var issues []string
	verified := 0

	for pkg, ver := range deps {
		if ver == "" {
			issues = append(issues, fmt.Sprintf("package %s has empty version constraint", pkg))
		} else {
			verified++
		}
	}
	return verified, issues, nil
}

// PackageArchive creates a publishable .tar.gz bundle of the package.
func (m *Manager) PackageArchive(outTarGzPath string) error {
	var buf bytes.Buffer
	gw := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gw)

	srcDir := filepath.Join(m.ProjectPath, "src")
	_ = filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(m.ProjectPath, path)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		header := &tar.Header{
			Name: rel,
			Mode: 0644,
			Size: int64(len(data)),
		}
		_ = tw.WriteHeader(header)
		_, _ = tw.Write(data)
		return nil
	})

	_ = tw.Close()
	_ = gw.Close()

	return os.WriteFile(outTarGzPath, buf.Bytes(), 0644)
}

func parseDependencies(yamlContent string) map[string]string {
	deps := make(map[string]string)
	lines := strings.Split(yamlContent, "\n")
	inDep := false

	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if strings.HasPrefix(trimmed, "dependencies:") {
			inDep = true
			continue
		}
		if inDep {
			if strings.HasPrefix(l, "  ") && strings.Contains(trimmed, ":") {
				parts := strings.SplitN(trimmed, ":", 2)
				if len(parts) == 2 {
					name := strings.TrimSpace(parts[0])
					ver := strings.Trim(strings.TrimSpace(parts[1]), "\"'")
					if name != "" && ver != "" && name != "{}" {
						deps[name] = ver
					}
				}
			} else if !strings.HasPrefix(l, " ") && trimmed != "" {
				inDep = false
			}
		}
	}
	return deps
}
