// Package manager implements the NilPM package and dependency management system for NilX.
package manager

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Manifest represents the parsed nilx.yaml project configuration.
type Manifest struct {
	Name         string            `json:"name"`
	Version      string            `json:"version"`
	Description  string            `json:"description"`
	Entry        string            `json:"entry"`
	Dependencies map[string]string `json:"dependencies"`
}

// Lockfile represents the locked dependency graph in nilx.lock.
type Lockfile struct {
	LockfileVersion int                    `json:"lockfileVersion"`
	GeneratedAt     string                 `json:"generatedAt"`
	Packages        map[string]PackageLock `json:"packages"`
}

type PackageLock struct {
	Version   string `json:"version"`
	Resolved  string `json:"resolved"`
	Integrity string `json:"integrity"`
}

// Manager handles dependency resolution and lockfile operations.
type Manager struct {
	ProjectPath string
}

func New(projectPath string) *Manager {
	return &Manager{ProjectPath: projectPath}
}

// Install reads dependencies and generates nilx.lock.
func (m *Manager) Install() error {
	manifestPath := filepath.Join(m.ProjectPath, "nilx.yaml")
	if _, err := os.Stat(manifestPath); os.IsNotExist(err) {
		return fmt.Errorf("no nilx.yaml manifest found at %s", manifestPath)
	}

	content, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}

	deps := parseDependencies(string(content))
	lock := Lockfile{
		LockfileVersion: 1,
		GeneratedAt:     time.Now().Format(time.RFC3339),
		Packages:        make(map[string]PackageLock),
	}

	for pkg, ver := range deps {
		h := sha256.Sum256([]byte(pkg + "@" + ver))
		hashStr := "sha256-" + hex.EncodeToString(h[:])
		cleanVer := strings.TrimPrefix(ver, "^")
		cleanVer = strings.TrimPrefix(cleanVer, "~")

		lock.Packages[pkg] = PackageLock{
			Version:   cleanVer,
			Resolved:  fmt.Sprintf("https://pkg.nilx.io/%s/-/%s-%s.tar.gz", pkg, pkg, cleanVer),
			Integrity: hashStr,
		}
	}

	// Write nilx.lock
	var sb strings.Builder
	sb.WriteString("# nilx.lock — Auto-generated by NilPM. Do not edit directly.\n")
	sb.WriteString(fmt.Sprintf("lockfile_version: %d\n", lock.LockfileVersion))
	sb.WriteString(fmt.Sprintf("generated_at: %q\n\n", lock.GeneratedAt))
	sb.WriteString("packages:\n")
	for pkg, pLock := range lock.Packages {
		sb.WriteString(fmt.Sprintf("  %s:\n", pkg))
		sb.WriteString(fmt.Sprintf("    version: %q\n", pLock.Version))
		sb.WriteString(fmt.Sprintf("    resolved: %q\n", pLock.Resolved))
		sb.WriteString(fmt.Sprintf("    integrity: %q\n", pLock.Integrity))
	}

	lockPath := filepath.Join(m.ProjectPath, "nilx.lock")
	return os.WriteFile(lockPath, []byte(sb.String()), 0644)
}

func parseDependencies(yamlContent string) map[string]string {
	deps := make(map[string]string)
	lines := strings.Split(yamlContent, "\n")
	inDep := false

	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if strings.HasPrefix(trimmed, "dependencies:") {
			inDep = true
			continue
		}
		if inDep {
			if strings.HasPrefix(l, "  ") && strings.Contains(trimmed, ":") {
				parts := strings.SplitN(trimmed, ":", 2)
				if len(parts) == 2 {
					name := strings.TrimSpace(parts[0])
					ver := strings.Trim(strings.TrimSpace(parts[1]), "\"'")
					if name != "" && ver != "" && name != "{}" {
						deps[name] = ver
					}
				}
			} else if !strings.HasPrefix(l, " ") && trimmed != "" {
				inDep = false
			}
		}
	}
	return deps
}
